In [29]:
include("testingC.jl");
using Symbolics, Graphs, GraphPlot, Latexify;

In [95]:
n = 5
c = 2;
r = Int(1+(c+1)*n+c*(1-c)/2)

A = randn(n+1, r);

getl, getL, sumL = makeSum(n, c);

In [96]:
X, Y, varTups, eqTups, basis, h = getReducedMat(A, c);

In [111]:
Y

48×45 Matrix{Num}:
 -h[1]   h[7]  -h[13]  h[19]  -h[25]  h[31]  …       0               0      0
 -h[2]   h[8]  -h[14]  h[20]  -h[26]  h[32]          0               0      0
 -h[3]   h[9]  -h[15]  h[21]  -h[27]  h[33]          0               0      0
 -h[4]  h[10]  -h[16]  h[22]  -h[28]  h[34]          0               0      0
 -h[5]  h[11]  -h[17]  h[23]  -h[29]  h[35]          0               0      0
 -h[6]  h[12]  -h[18]  h[24]  -h[30]  h[36]  …       0               0      0
     0  -h[1]       0      0       0   h[7]          0               0      0
     0  -h[2]       0      0       0   h[8]          0               0      0
     0  -h[3]       0      0       0   h[9]          0               0      0
     0  -h[4]       0      0       0  h[10]          0               0      0
     0  -h[5]       0      0       0  h[11]  …       0               0      0
     0  -h[6]       0      0       0  h[12]          0               0      0
     0      0   -h[2]   h[1]       0      0  

In [99]:
varInds = []
for (i, var) in enumerate(varTups)
    if sum([x for x in var][1:c]) == 3
        push!(varInds, i)
    end 
end

In [100]:
Z2 = Y[:, setdiff(1:size(Y)[2], varInds)];

In [103]:
eqInds = []
for (i, eqTup) in enumerate(eqTups)
    if !(eqTup[1][1] isa Number)
        push!(eqInds, i)
    end
end

Z1_ = Y[eqInds, varInds];

In [107]:
Id = diagm(ones(size(Z1_)[1]));

In [108]:
Z1 = copy(Z1_)
for (i, eqInd) in enumerate(eqInds)
    Z1 = hcat(Z1[:, 1:eqInd-1], -h[1]*Id[:, i], Z1[:, eqInd:end])
end

In [112]:
Z1

24×48 Matrix{Num}:
 -h[14]  h[13] + h[20]         -h[26]  …      0.0      0.0      0.0      0.0
 -h[16]  h[14] + h[22]         -h[28]         0.0      0.0      0.0      0.0
 -h[17]  h[15] + h[23]         -h[29]         0.0      0.0      0.0      0.0
 -h[15]          h[21]  h[13] - h[27]         0.0      0.0      0.0      0.0
 -h[17]          h[23]  h[14] - h[29]         0.0      0.0      0.0      0.0
 -h[18]          h[24]  h[15] - h[30]  …      0.0      0.0      0.0      0.0
      0         -h[17]          h[16]         0.0      0.0      0.0      0.0
      0         -h[18]          h[17]         0.0      0.0      0.0      0.0
      0              0              0         0.0      0.0      0.0      0.0
      0              0              0         0.0      0.0      0.0      0.0
      0              0              0  …      0.0      0.0      0.0      0.0
      0              0              0         0.0      0.0      0.0      0.0
      0              0              0         0.0      0.

In [113]:
Z2

48×21 Matrix{Num}:
 -h[1]   h[7]  -h[13]  h[19]  -h[25]  h[31]  …      0       0       0       0
 -h[2]   h[8]  -h[14]  h[20]  -h[26]  h[32]         0       0       0       0
 -h[3]   h[9]  -h[15]  h[21]  -h[27]  h[33]         0       0       0       0
 -h[4]  h[10]  -h[16]  h[22]  -h[28]  h[34]         0       0       0       0
 -h[5]  h[11]  -h[17]  h[23]  -h[29]  h[35]         0       0       0       0
 -h[6]  h[12]  -h[18]  h[24]  -h[30]  h[36]  …      0       0       0       0
     0  -h[1]       0      0       0   h[7]         0       0       0       0
     0  -h[2]       0      0       0   h[8]         0       0       0       0
     0  -h[3]       0      0       0   h[9]         0       0       0       0
     0  -h[4]       0      0       0  h[10]         0       0       0       0
     0  -h[5]       0      0       0  h[11]  …      0       0       0       0
     0  -h[6]       0      0       0  h[12]         0       0       0       0
     0      0   -h[2]   h[1]       0      0  

In [110]:
Symbolics.expand.(-Z1*Z2)

24×21 Matrix{Num}:
 -h[1]*h[14] + h[13]*h[2] - h[19]*h[4] + h[2]*h[20] + h[25]*h[5] - h[26]*h[3]    …                                                                                                0.0
 -h[1]*h[16] + h[14]*h[2] + h[2]*h[22] - h[20]*h[4] + h[26]*h[5] - h[28]*h[3]                                                                                                     0.0
 -h[1]*h[17] + h[15]*h[2] + h[2]*h[23] - h[21]*h[4] + h[27]*h[5] - h[29]*h[3]                                                                                                     0.0
 -h[1]*h[15] + h[13]*h[3] - h[19]*h[5] + h[2]*h[21] + h[25]*h[6] - h[27]*h[3]                                                                                                     0.0
 -h[1]*h[17] + h[14]*h[3] + h[2]*h[23] - h[20]*h[5] + h[26]*h[6] - h[29]*h[3]                                                                                                     0.0
 -h[1]*h[18] + h[15]*h[3] + h[2]*h[24] - h[21]*h[5] + h[27]*h[6] - h[3]